site_name: Документация Comsign PWA
theme:
  name: readthedocs

extra:
  favicon: assets/pwa_icon.png

docs_dir: docs

nav:
  - Обзор: overview.md
  - Быстрый старт: start.md
  - Личный кабинет: clients_area.md
  - Главная: sections/main.md
  - Конструктор: sections/builder.md
  - Пуши: sections/push.md
  - Статистика: sections/statistics.md

site_url: !ENV READTHEDOCS_CANONICAL_URL

extra_css:
  - custom/styles.css


markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
