site_name: Документация Comsign PWA
theme:
  name: readthedocs

extra_css:
  - custom/styles.css

docs_dir: docs

nav:
  - Обзор: overview.md
  - Главная: sections/main.md
  - Конструктор: sections/builder.md
  - Статистика: sections/statistics.md
  - Пуши: sections/push.md

site_url: !ENV READTHEDOCS_CANONICAL_URL