site_name: Документация Comsign PWA
theme:
  name: readthedocs

extra_css:
  - custom/styles.css

docs_dir: docs

nav:
  - Главная: index.md
  - Обзор: overview.md

site_url: !ENV READTHEDOCS_CANONICAL_URL