site_name: Документация Comsign PWA
theme:
  name: readthedocs

docs_dir: docs

nav:
  - Обзор: overview.md
  - Главная: sections/main.md
  - Конструктор: sections/builder.md
  - Статистика: sections/statistics.md
  - Пуши: sections/push.md

site_url: !ENV READTHEDOCS_CANONICAL_URL

# extra_css:
#   - custom/styles.css


markdown_extensions:
  - attr_list
  - toc:
      permalink: true
