site_name: Документация Comsign PWA
theme:
  name: readthedocs
  logo: assets/logo2.png
  favicon: assets/favicon.png

extra:
  homepage: https://comsign.io

# extra:
#   favicon: assets/pwa_icon.png

docs_dir: docs

nav:
  - Обзор: overview.md
  - Быстрый старт: start.md
  - Главная: main.md
  - Конструктор: sections/builder.md
  - Push-уведомления: sections/push.md
  - Статистика: sections/statistics.md

site_url: !ENV READTHEDOCS_CANONICAL_URL

extra_css:
  - custom/styles.css

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - js/hide-ads.js
